/*
 * Generated by Bluespec Compiler (build e76ca21)
 * 
 * On Mon Dec 28 13:16:08 CET 2020
 * 
 */

/* Generation options: */
#ifndef __mkAXIMultiplier_tb_h__
#define __mkAXIMultiplier_tb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkAXIMultiplier.h"


/* Class declaration for the mkAXIMultiplier_tb module */
class MOD_mkAXIMultiplier_tb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt32> INST_m_rd_araddrOut;
  MOD_Wire<tUInt8> INST_m_rd_arprotOut;
  MOD_Wire<tUInt8> INST_m_rd_arreadyIn;
  MOD_CReg<tUInt64> INST_m_rd_in_rv;
  MOD_Reg<tUInt8> INST_m_rd_isRst_isInReset;
  MOD_CReg<tUWide> INST_m_rd_out_rv;
  MOD_Wire<tUInt64> INST_m_rd_rdataIn;
  MOD_Wire<tUInt8> INST_m_rd_rrespIn;
  MOD_Wire<tUInt8> INST_m_rd_rvalidIn;
  MOD_CReg<tUInt64> INST_m_wr_addrOut_rv;
  MOD_Wire<tUInt32> INST_m_wr_awaddrOut;
  MOD_Wire<tUInt8> INST_m_wr_awprotOut;
  MOD_Wire<tUInt8> INST_m_wr_awreadyIn;
  MOD_Wire<tUInt8> INST_m_wr_brespIn;
  MOD_Wire<tUInt8> INST_m_wr_bvalidIn;
  MOD_CReg<tUWide> INST_m_wr_dataOut_rv;
  MOD_CReg<tUWide> INST_m_wr_in_rv;
  MOD_Reg<tUInt8> INST_m_wr_isRst_isInReset;
  MOD_CReg<tUInt8> INST_m_wr_out_rv;
  MOD_Wire<tUInt64> INST_m_wr_wdataOut;
  MOD_Wire<tUInt8> INST_m_wr_wreadyIn;
  MOD_Wire<tUInt8> INST_m_wr_wstrbOut;
  MOD_mkAXIMultiplier INST_s_mul;
  MOD_Reg<tUInt8> INST_testState;
 
 /* Constructor */
 public:
  MOD_mkAXIMultiplier_tb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_m_wr_dataOut_rv_port1__read__5_BIT_72___d46;
  tUInt8 DEF_m_wr_addrOut_rv_port1__read__7_BIT_35___d38;
  tUInt8 DEF_m_wr_isRst_isInReset__h1294;
  tUInt8 DEF_m_rd_in_rv_port1__read_BIT_35___d3;
  tUInt8 DEF_m_rd_isRst_isInReset__h119;
  tUWide DEF_m_wr_in_rv_port1__read____d21;
  tUWide DEF_m_wr_in_rv_port0__read____d92;
  tUWide DEF_m_wr_dataOut_rv_port1__read____d45;
  tUWide DEF_m_wr_dataOut_rv_port0__read____d26;
  tUWide DEF_m_rd_out_rv_port1__read____d113;
  tUWide DEF_m_rd_out_rv_port0__read____d11;
  tUInt64 DEF_m_wr_addrOut_rv_port1__read____d37;
  tUInt64 DEF_m_rd_in_rv_port1__read____d2;
  tUInt8 DEF_b__h4068;
  tUInt8 DEF_m_wr_out_rv_port1__read____d99;
  tUInt8 DEF_NOT_m_wr_out_rv_port0__read__3_BIT_2_4___d55;
  tUInt8 DEF_NOT_m_wr_isRst_isInReset_0___d39;
  tUInt8 DEF_NOT_m_rd_out_rv_port0__read__1_BIT_66_2___d13;
  tUInt8 DEF_NOT_m_rd_isRst_isInReset___d4;
 
 /* Local definitions */
 private:
  tUWide DEF_m_wr_in_rv_port1__read__1_BITS_74_TO_3___d35;
  tUInt8 DEF_m_wr_out_rv_port1__read__9_BITS_1_TO_0_05_EQ_0___d106;
  tUInt8 DEF_testState_5_PLUS_1___d98;
  tUWide DEF__0_CONCAT_DONTCARE___d31;
  tUWide DEF__1_CONCAT_m_wr_in_rv_port1__read__1_BITS_74_TO_3_5___d36;
  tUWide DEF__0_CONCAT_DONTCARE___d50;
  tUWide DEF__1_CONCAT_m_rd_rdataIn_wget__7_CONCAT_m_rd_rres_ETC___d19;
  tUWide DEF__0_CONCAT_DONTCARE___d117;
  tUInt64 DEF__0_CONCAT_DONTCARE___d8;
  tUInt8 DEF__0_CONCAT_DONTCARE___d104;
 
 /* Rules */
 public:
  void RL_m_rd_isRst_isResetAssertedUpdate();
  void RL_m_rd_deqIn();
  void RL_m_rd_forwardIn();
  void RL_m_rd_enqOut();
  void RL_m_wr_isRst_isResetAssertedUpdate();
  void RL_m_wr_splitAddrData();
  void RL_m_wr_deqAddr();
  void RL_m_wr_forwardAddr();
  void RL_m_wr_deqData();
  void RL_m_wr_forwardData();
  void RL_m_wr_forwardResp();
  void RL_forward1();
  void RL_forward2();
  void RL_forward3();
  void RL_forward4();
  void RL_forward5();
  void RL_forward6();
  void RL_forward7();
  void RL_forward8();
  void RL_forward1_1();
  void RL_forward2_1();
  void RL_forward3_1();
  void RL_forward4_1();
  void RL_forward5_1();
  void RL_forward6_1();
  void RL_forward7_1();
  void RL_forward8_1();
  void RL_forward9();
  void RL_forward10();
  void RL_forward11();
  void RL_write_register1();
  void RL_write_register2();
  void RL_read_register3();
  void RL_read_register4();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAXIMultiplier_tb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkAXIMultiplier_tb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkAXIMultiplier_tb &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkAXIMultiplier_tb &backing);
};

#endif /* ifndef __mkAXIMultiplier_tb_h__ */
