/*
 * Generated by Bluespec Compiler (build e76ca21)
 * 
 * On Mon Dec 28 13:16:08 CET 2020
 * 
 */

/* Generation options: */
#ifndef __mkAXIMultiplier_h__
#define __mkAXIMultiplier_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkAXIMultiplier module */
class MOD_mkAXIMultiplier : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt64> INST_operand_1;
  MOD_Reg<tUInt64> INST_operand_2;
  MOD_Reg<tUInt64> INST_product;
  MOD_Wire<tUInt32> INST_slave_read_araddrIn;
  MOD_Wire<tUInt8> INST_slave_read_arprotIn;
  MOD_Wire<tUInt8> INST_slave_read_arvalidIn;
  MOD_Fifo<tUInt64> INST_slave_read_in;
  MOD_Reg<tUInt8> INST_slave_read_isRst_isInReset;
  MOD_Fifo<tUWide> INST_slave_read_out;
  MOD_Wire<tUInt64> INST_slave_read_rdataOut;
  MOD_Wire<tUInt8> INST_slave_read_rreadyIn;
  MOD_Wire<tUInt8> INST_slave_read_rrespOut;
  MOD_CReg<tUInt64> INST_slave_write_addrIn_rv;
  MOD_Wire<tUInt32> INST_slave_write_awaddrIn;
  MOD_Wire<tUInt8> INST_slave_write_awprotIn;
  MOD_Wire<tUInt8> INST_slave_write_awvalidIn;
  MOD_Wire<tUInt8> INST_slave_write_breadyIn;
  MOD_Wire<tUInt8> INST_slave_write_brespOut;
  MOD_CReg<tUWide> INST_slave_write_dataIn_rv;
  MOD_Fifo<tUWide> INST_slave_write_in;
  MOD_Reg<tUInt8> INST_slave_write_isRst_isInReset;
  MOD_Fifo<tUInt8> INST_slave_write_out;
  MOD_Wire<tUInt64> INST_slave_write_wdataIn;
  MOD_Wire<tUInt8> INST_slave_write_wstrbIn;
  MOD_Wire<tUInt8> INST_slave_write_wvalidIn;
 
 /* Constructor */
 public:
  MOD_mkAXIMultiplier(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_aresetn;
 
 /* Port definitions */
 public:
  tUInt8 PORT_S00_AXI_arready;
  tUInt8 PORT_S00_AXI_rvalid;
  tUInt64 PORT_S00_AXI_rdata;
  tUInt8 PORT_S00_AXI_rresp;
  tUInt8 PORT_S00_AXI_awready;
  tUInt8 PORT_S00_AXI_wready;
  tUInt8 PORT_S00_AXI_bvalid;
  tUInt8 PORT_S00_AXI_bresp;
  tUInt8 PORT_RDY_S00_AXI_arready;
  tUInt8 PORT_RDY_S00_AXI_parvalid;
  tUInt8 PORT_RDY_S00_AXI_paraddr;
  tUInt8 PORT_RDY_S00_AXI_parprot;
  tUInt8 PORT_RDY_S00_AXI_rvalid;
  tUInt8 PORT_RDY_S00_AXI_prready;
  tUInt8 PORT_RDY_S00_AXI_rdata;
  tUInt8 PORT_RDY_S00_AXI_rresp;
  tUInt8 PORT_RDY_S00_AXI_awready;
  tUInt8 PORT_RDY_S00_AXI_pawvalid;
  tUInt8 PORT_RDY_S00_AXI_pawaddr;
  tUInt8 PORT_RDY_S00_AXI_pawprot;
  tUInt8 PORT_RDY_S00_AXI_wready;
  tUInt8 PORT_RDY_S00_AXI_pwvalid;
  tUInt8 PORT_RDY_S00_AXI_pwdata;
  tUInt8 PORT_RDY_S00_AXI_pwstrb;
  tUInt8 PORT_RDY_S00_AXI_bvalid;
  tUInt8 PORT_RDY_S00_AXI_pbready;
  tUInt8 PORT_RDY_S00_AXI_bresp;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_slave_write_isRst_isInReset__h869;
  tUInt8 DEF_slave_read_isRst_isInReset__h80;
  tUWide DEF_slave_write_dataIn_rv_port1__read____d24;
  tUWide DEF_slave_write_dataIn_rv_port0__read____d45;
  tUInt64 DEF_slave_write_addrIn_rv_port1__read____d22;
  tUInt8 DEF_slave_write_out_notEmpty____d57;
  tUInt8 DEF_slave_read_out_notEmpty____d15;
  tUInt8 DEF_slave_read_in_notFull____d6;
  tUInt8 DEF_NOT_slave_write_dataIn_rv_port0__read__5_BIT_72_6___d47;
  tUInt8 DEF_NOT_slave_write_addrIn_rv_port0__read__5_BIT_35_6___d37;
  tUInt8 DEF_NOT_slave_write_isRst_isInReset_1___d38;
  tUInt8 DEF_NOT_slave_read_isRst_isInReset___d3;
 
 /* Local definitions */
 private:
  tUWide DEF_slave_write_in_first____d80;
  tUWide DEF_slave_read_out_first____d18;
  tUInt64 DEF_x_data__h2857;
  tUInt64 DEF_x_data__h2827;
  tUWide DEF_slave_write_dataIn_rv_port1__read__4_BITS_71_TO_0___d32;
  tUWide DEF_operand_1_1_MUL_operand_2_2___d86;
  tUWide DEF_slave_write_addrIn_rv_port1__read__2_BITS_34_T_ETC___d34;
  tUWide DEF__1_CONCAT_slave_write_wdataIn_wget__1_CONCAT_sl_ETC___d53;
  tUWide DEF__0_CONCAT_DONTCARE___d30;
  tUWide DEF_IF_slave_read_in_first__4_BITS_8_TO_3_5_EQ_0_6_ETC___d76;
 
 /* Rules */
 public:
  void RL_slave_read_isRst_isResetAssertedUpdate();
  void RL_slave_read_addrInWrite();
  void RL_slave_read_deqOut();
  void RL_slave_read_putOutData();
  void RL_slave_write_isRst_isResetAssertedUpdate();
  void RL_slave_write_mergeAddrData();
  void RL_slave_write_addrInWrite();
  void RL_slave_write_dataInWrite();
  void RL_slave_write_outWrite();
  void RL_slave_write_outForward();
  void RL_handleReadRequest();
  void RL_handleWriteRequest();
  void RL_product_operation();
 
 /* Methods */
 public:
  tUInt8 METH_slave_read_fab_arready();
  tUInt8 METH_RDY_slave_read_fab_arready();
  void METH_slave_read_fab_parvalid(tUInt8 ARG_S00_AXI_arvalid);
  tUInt8 METH_RDY_slave_read_fab_parvalid();
  void METH_slave_read_fab_paraddr(tUInt32 ARG_S00_AXI_araddr);
  tUInt8 METH_RDY_slave_read_fab_paraddr();
  void METH_slave_read_fab_parprot(tUInt8 ARG_S00_AXI_arprot);
  tUInt8 METH_RDY_slave_read_fab_parprot();
  tUInt8 METH_slave_read_fab_rvalid();
  tUInt8 METH_RDY_slave_read_fab_rvalid();
  void METH_slave_read_fab_prready(tUInt8 ARG_S00_AXI_rready);
  tUInt8 METH_RDY_slave_read_fab_prready();
  tUInt64 METH_slave_read_fab_rdata();
  tUInt8 METH_RDY_slave_read_fab_rdata();
  tUInt8 METH_slave_read_fab_rresp();
  tUInt8 METH_RDY_slave_read_fab_rresp();
  tUInt8 METH_slave_write_fab_awready();
  tUInt8 METH_RDY_slave_write_fab_awready();
  void METH_slave_write_fab_pawvalid(tUInt8 ARG_S00_AXI_awvalid);
  tUInt8 METH_RDY_slave_write_fab_pawvalid();
  void METH_slave_write_fab_pawaddr(tUInt32 ARG_S00_AXI_awaddr);
  tUInt8 METH_RDY_slave_write_fab_pawaddr();
  void METH_slave_write_fab_pawprot(tUInt8 ARG_S00_AXI_awprot);
  tUInt8 METH_RDY_slave_write_fab_pawprot();
  tUInt8 METH_slave_write_fab_wready();
  tUInt8 METH_RDY_slave_write_fab_wready();
  void METH_slave_write_fab_pwvalid(tUInt8 ARG_S00_AXI_wvalid);
  tUInt8 METH_RDY_slave_write_fab_pwvalid();
  void METH_slave_write_fab_pwdata(tUInt64 ARG_S00_AXI_wdata);
  tUInt8 METH_RDY_slave_write_fab_pwdata();
  void METH_slave_write_fab_pwstrb(tUInt8 ARG_S00_AXI_wstrb);
  tUInt8 METH_RDY_slave_write_fab_pwstrb();
  tUInt8 METH_slave_write_fab_bvalid();
  tUInt8 METH_RDY_slave_write_fab_bvalid();
  void METH_slave_write_fab_pbready(tUInt8 ARG_S00_AXI_bready);
  tUInt8 METH_RDY_slave_write_fab_pbready();
  tUInt8 METH_slave_write_fab_bresp();
  tUInt8 METH_RDY_slave_write_fab_bresp();
 
 /* Reset routines */
 public:
  void reset_aresetn(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAXIMultiplier &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkAXIMultiplier &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkAXIMultiplier &backing);
};

#endif /* ifndef __mkAXIMultiplier_h__ */
