/*
 * Generated by Bluespec Compiler (build 503820f)
 * 
 * On Sun Dec 27 10:42:08 UTC 2020
 * 
 */

/* Generation options: */
#ifndef __model_mkAXIConverter_tb_h__
#define __model_mkAXIConverter_tb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkAXIConverter_tb.h"

/* Class declaration for a model of mkAXIConverter_tb */
class MODEL_mkAXIConverter_tb : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkAXIConverter_tb *mkAXIConverter_tb_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkAXIConverter_tb();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkAXIConverter_tb();
}

#endif /* ifndef __model_mkAXIConverter_tb_h__ */
