/*
 * Generated by Bluespec Compiler (build e76ca21)
 * 
 * On Mon Dec 28 13:16:08 CET 2020
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkAXIMultiplier_tb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkAXIMultiplier_tb::MODEL_mkAXIMultiplier_tb()
{
  mkAXIMultiplier_tb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkAXIMultiplier_tb()
{
  MODEL_mkAXIMultiplier_tb *model = new MODEL_mkAXIMultiplier_tb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkAXIMultiplier_tb &INST_top = *((MOD_mkAXIMultiplier_tb *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_slave_read_out_i_notEmpty____d12;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_slave_write_out_i_notEmpty____d54;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_addrInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_addrInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_deqOut;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_deqOut;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_putOutData;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_putOutData;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_mergeAddrData;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_mergeAddrData;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_addrInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_addrInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_dataInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_dataInWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outWrite;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outForward;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outForward;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleReadRequest;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleReadRequest;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleWriteRequest;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleWriteRequest;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_product_operation;
	 tUInt8 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_product_operation;
	 tUInt8 DEF_INST_top_DEF_NOT_m_wr_in_rv_port0__read__2_BIT_107_3___d94;
	 tUInt8 DEF_INST_top_DEF_m_wr_out_rv_port1__read__9_BIT_2___d100;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_deqIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_deqIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_forwardIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_forwardIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_enqOut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_enqOut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_isRst_isResetAssertedUpdate;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_splitAddrData;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_splitAddrData;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqAddr;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqAddr;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardAddr;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardAddr;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqData;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqData;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardData;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardData;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardResp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardResp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward6;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward6;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward8;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward8;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward1_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward1_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward2_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward2_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward3_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward3_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward4_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward4_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward5_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward5_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward6_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward6_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward7_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward7_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward8_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward8_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_forward11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_forward11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_write_register1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_write_register1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_write_register2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_write_register2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_read_register3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_read_register3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_read_register4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_read_register4;
	 INST_top.INST_s_mul.METH_RDY_slave_read_fab_parvalid();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward1;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pbready();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward10 = DEF_INST_top_DEF_CAN_FIRE_RL_forward10;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward11 = DEF_INST_top_DEF_CAN_FIRE_RL_forward11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward1_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward1_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward1_1;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pawvalid();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward2_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward2_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward2_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward2 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward2 = DEF_INST_top_DEF_CAN_FIRE_RL_forward2;
	 INST_top.INST_s_mul.METH_RDY_slave_read_fab_paraddr();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward3 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward3 = DEF_INST_top_DEF_CAN_FIRE_RL_forward3;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pawaddr();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward3_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward3_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward3_1;
	 INST_top.INST_s_mul.METH_RDY_slave_read_fab_parprot();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward4 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward4 = DEF_INST_top_DEF_CAN_FIRE_RL_forward4;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pawprot();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward4_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward4_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward4_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward5_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward5_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward5_1;
	 INST_top.INST_s_mul.METH_RDY_slave_read_fab_prready();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward5 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward5 = DEF_INST_top_DEF_CAN_FIRE_RL_forward5;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward6 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward6 = DEF_INST_top_DEF_CAN_FIRE_RL_forward6;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward7 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward7 = DEF_INST_top_DEF_CAN_FIRE_RL_forward7;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pwvalid();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward6_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward6_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward6_1;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pwdata();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward7_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward7_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward7_1;
	 INST_top.INST_s_mul.METH_RDY_slave_write_fab_pwstrb();
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward8_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward8_1 = DEF_INST_top_DEF_CAN_FIRE_RL_forward8_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward8 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward8 = DEF_INST_top_DEF_CAN_FIRE_RL_forward8;
	 DEF_INST_top_DEF_CAN_FIRE_RL_forward9 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_forward9 = DEF_INST_top_DEF_CAN_FIRE_RL_forward9;
	 INST_top.DEF_m_rd_isRst_isInReset__h119 = INST_top.INST_m_rd_isRst_isInReset.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_isRst_isResetAssertedUpdate = INST_top.DEF_m_rd_isRst_isInReset__h119;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_isRst_isResetAssertedUpdate = DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_isRst_isResetAssertedUpdate;
	 INST_top.DEF_m_wr_isRst_isInReset__h1294 = INST_top.INST_m_wr_isRst_isInReset.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_isRst_isResetAssertedUpdate = INST_top.DEF_m_wr_isRst_isInReset__h1294;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_isRst_isResetAssertedUpdate = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_product_operation = (tUInt8)1u;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_product_operation = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_product_operation;
	 INST_top.DEF_m_wr_in_rv_port0__read____d92 = INST_top.INST_m_wr_in_rv.METH_port0__read();
	 INST_top.DEF_b__h4068 = INST_top.INST_testState.METH_read();
	 DEF_INST_top_DEF_NOT_m_wr_in_rv_port0__read__2_BIT_107_3___d94 = !INST_top.DEF_m_wr_in_rv_port0__read____d92.get_bits_in_word8(3u,
																	11u,
																	1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_write_register1 = DEF_INST_top_DEF_NOT_m_wr_in_rv_port0__read__2_BIT_107_3___d94 && (INST_top.DEF_b__h4068) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_write_register1 = DEF_INST_top_DEF_CAN_FIRE_RL_write_register1;
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleReadRequest = INST_top.INST_s_mul.INST_slave_read_in.METH_i_notEmpty() && INST_top.INST_s_mul.INST_slave_read_out.METH_i_notFull();
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleReadRequest = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleReadRequest;
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleWriteRequest = INST_top.INST_s_mul.INST_slave_write_in.METH_i_notEmpty() && INST_top.INST_s_mul.INST_slave_write_out.METH_i_notFull();
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleWriteRequest = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_handleWriteRequest;
	 INST_top.INST_s_mul.DEF_slave_read_isRst_isInReset__h80 = INST_top.INST_s_mul.INST_slave_read_isRst_isInReset.METH_read();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_isRst_isResetAssertedUpdate = INST_top.INST_s_mul.DEF_slave_read_isRst_isInReset__h80;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_isRst_isResetAssertedUpdate = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_slave_read_out_i_notEmpty____d12 = INST_top.INST_s_mul.INST_slave_read_out.METH_i_notEmpty();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_putOutData = DEF_INST_top_INST_s_mul_DEF_slave_read_out_i_notEmpty____d12;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_putOutData = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_putOutData;
	 INST_top.INST_s_mul.DEF_slave_write_isRst_isInReset__h869 = INST_top.INST_s_mul.INST_slave_write_isRst_isInReset.METH_read();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_isRst_isResetAssertedUpdate = INST_top.INST_s_mul.DEF_slave_write_isRst_isInReset__h869;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_isRst_isResetAssertedUpdate = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_slave_write_out_i_notEmpty____d54 = INST_top.INST_s_mul.INST_slave_write_out.METH_i_notEmpty();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outForward = DEF_INST_top_INST_s_mul_DEF_slave_write_out_i_notEmpty____d54;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outForward = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outForward;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward10)
	   INST_top.RL_forward10();
	 INST_top.INST_s_mul.DEF_slave_write_out_notEmpty____d57 = INST_top.INST_s_mul.INST_slave_write_out.METH_notEmpty();
	 INST_top.INST_s_mul.DEF_NOT_slave_write_isRst_isInReset_1___d38 = !(INST_top.INST_s_mul.DEF_slave_write_isRst_isInReset__h869);
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outWrite = DEF_INST_top_INST_s_mul_DEF_slave_write_out_i_notEmpty____d54 && ((INST_top.INST_s_mul.DEF_NOT_slave_write_isRst_isInReset_1___d38 && INST_top.INST_s_mul.INST_slave_write_breadyIn.METH_wget()) && INST_top.INST_s_mul.DEF_slave_write_out_notEmpty____d57);
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outWrite = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_outWrite;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward1_1)
	   INST_top.RL_forward1_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward2)
	   INST_top.RL_forward2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward5)
	   INST_top.RL_forward5();
	 INST_top.INST_s_mul.DEF_slave_read_out_notEmpty____d15 = INST_top.INST_s_mul.INST_slave_read_out.METH_notEmpty();
	 INST_top.INST_s_mul.DEF_NOT_slave_read_isRst_isInReset___d3 = !(INST_top.INST_s_mul.DEF_slave_read_isRst_isInReset__h80);
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_deqOut = DEF_INST_top_INST_s_mul_DEF_slave_read_out_i_notEmpty____d12 && ((INST_top.INST_s_mul.DEF_NOT_slave_read_isRst_isInReset___d3 && INST_top.INST_s_mul.INST_slave_read_rreadyIn.METH_wget()) && INST_top.INST_s_mul.DEF_slave_read_out_notEmpty____d15);
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_deqOut = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_deqOut;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward5_1)
	   INST_top.RL_forward5_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward6)
	   INST_top.RL_forward6();
	 INST_top.DEF_m_rd_out_rv_port0__read____d11 = INST_top.INST_m_rd_out_rv.METH_port0__read();
	 INST_top.DEF_NOT_m_rd_out_rv_port0__read__1_BIT_66_2___d13 = !INST_top.DEF_m_rd_out_rv_port0__read____d11.get_bits_in_word8(2u,
																     2u,
																     1u);
	 INST_top.DEF_NOT_m_rd_isRst_isInReset___d4 = !(INST_top.DEF_m_rd_isRst_isInReset__h119);
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_enqOut = INST_top.DEF_NOT_m_rd_out_rv_port0__read__1_BIT_66_2___d13 && (INST_top.DEF_NOT_m_rd_isRst_isInReset___d4 && INST_top.INST_m_rd_rvalidIn.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_enqOut = DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_enqOut;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward9)
	   INST_top.RL_forward9();
	 INST_top.DEF_NOT_m_wr_out_rv_port0__read__3_BIT_2_4___d55 = !((tUInt8)(INST_top.INST_m_wr_out_rv.METH_port0__read() >> 2u));
	 INST_top.DEF_NOT_m_wr_isRst_isInReset_0___d39 = !(INST_top.DEF_m_wr_isRst_isInReset__h1294);
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardResp = INST_top.DEF_NOT_m_wr_out_rv_port0__read__3_BIT_2_4___d55 && (INST_top.DEF_NOT_m_wr_isRst_isInReset_0___d39 && INST_top.INST_m_wr_bvalidIn.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardResp = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardResp;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_write_register1)
	   INST_top.RL_write_register1();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_isRst_isResetAssertedUpdate)
	   INST_top.INST_s_mul.RL_slave_read_isRst_isResetAssertedUpdate();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_putOutData)
	   INST_top.INST_s_mul.RL_slave_read_putOutData();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward7)
	   INST_top.RL_forward7();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward8)
	   INST_top.RL_forward8();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_enqOut)
	   INST_top.RL_m_rd_enqOut();
	 INST_top.DEF_m_rd_out_rv_port1__read____d113 = INST_top.INST_m_rd_out_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_read_register4 = (INST_top.DEF_m_rd_out_rv_port1__read____d113.get_bits_in_word8(2u,
														       2u,
														       1u) && (INST_top.DEF_b__h4068) == (tUInt8)3u) && !DEF_INST_top_DEF_CAN_FIRE_RL_write_register1;
	 DEF_INST_top_DEF_WILL_FIRE_RL_read_register4 = DEF_INST_top_DEF_CAN_FIRE_RL_read_register4;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_read_register4)
	   INST_top.RL_read_register4();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_deqOut)
	   INST_top.INST_s_mul.RL_slave_read_deqOut();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_isRst_isResetAssertedUpdate)
	   INST_top.INST_s_mul.RL_slave_write_isRst_isResetAssertedUpdate();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outForward)
	   INST_top.INST_s_mul.RL_slave_write_outForward();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward11)
	   INST_top.RL_forward11();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardResp)
	   INST_top.RL_m_wr_forwardResp();
	 INST_top.DEF_m_wr_out_rv_port1__read____d99 = INST_top.INST_m_wr_out_rv.METH_port1__read();
	 DEF_INST_top_DEF_m_wr_out_rv_port1__read__9_BIT_2___d100 = (tUInt8)((INST_top.DEF_m_wr_out_rv_port1__read____d99) >> 2u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_read_register3 = ((DEF_INST_top_DEF_m_wr_out_rv_port1__read__9_BIT_2___d100 && !((tUInt8)(INST_top.INST_m_rd_in_rv.METH_port0__read() >> 35u))) && (INST_top.DEF_b__h4068) == (tUInt8)2u) && !(DEF_INST_top_DEF_CAN_FIRE_RL_read_register4 || DEF_INST_top_DEF_CAN_FIRE_RL_write_register1);
	 DEF_INST_top_DEF_WILL_FIRE_RL_read_register3 = DEF_INST_top_DEF_CAN_FIRE_RL_read_register3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_write_register2 = ((DEF_INST_top_DEF_m_wr_out_rv_port1__read__9_BIT_2___d100 && DEF_INST_top_DEF_NOT_m_wr_in_rv_port0__read__2_BIT_107_3___d94) && (INST_top.DEF_b__h4068) == (tUInt8)1u) && !(DEF_INST_top_DEF_CAN_FIRE_RL_read_register4 || DEF_INST_top_DEF_CAN_FIRE_RL_write_register1);
	 DEF_INST_top_DEF_WILL_FIRE_RL_write_register2 = DEF_INST_top_DEF_CAN_FIRE_RL_write_register2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_read_register3)
	   INST_top.RL_read_register3();
	 INST_top.DEF_m_rd_in_rv_port1__read____d2 = INST_top.INST_m_rd_in_rv.METH_port1__read();
	 INST_top.DEF_m_rd_in_rv_port1__read_BIT_35___d3 = (tUInt8)((INST_top.DEF_m_rd_in_rv_port1__read____d2) >> 35u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_deqIn = INST_top.DEF_m_rd_in_rv_port1__read_BIT_35___d3 && (INST_top.DEF_NOT_m_rd_isRst_isInReset___d4 && INST_top.INST_m_rd_arreadyIn.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_deqIn = DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_deqIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_forwardIn = INST_top.DEF_m_rd_in_rv_port1__read_BIT_35___d3;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_forwardIn = DEF_INST_top_DEF_CAN_FIRE_RL_m_rd_forwardIn;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward1)
	   INST_top.RL_forward1();
	 INST_top.INST_s_mul.DEF_slave_read_in_notFull____d6 = INST_top.INST_s_mul.INST_slave_read_in.METH_notFull();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_addrInWrite = (INST_top.INST_s_mul.INST_slave_read_in.METH_i_notFull() && ((INST_top.INST_s_mul.DEF_NOT_slave_read_isRst_isInReset___d3 && INST_top.INST_s_mul.INST_slave_read_arvalidIn.METH_wget()) && INST_top.INST_s_mul.DEF_slave_read_in_notFull____d6)) && !DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_addrInWrite = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_read_addrInWrite;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_forwardIn)
	   INST_top.RL_m_rd_forwardIn();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward3)
	   INST_top.RL_forward3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward4)
	   INST_top.RL_forward4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_deqIn)
	   INST_top.RL_m_rd_deqIn();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_rd_isRst_isResetAssertedUpdate)
	   INST_top.RL_m_rd_isRst_isResetAssertedUpdate();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_write_register2)
	   INST_top.RL_write_register2();
	 INST_top.DEF_m_wr_in_rv_port1__read____d21 = INST_top.INST_m_wr_in_rv.METH_port1__read();
	 INST_top.DEF_m_wr_dataOut_rv_port0__read____d26 = INST_top.INST_m_wr_dataOut_rv.METH_port0__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_splitAddrData = INST_top.DEF_m_wr_in_rv_port1__read____d21.get_bits_in_word8(3u,
															11u,
															1u) && (!((tUInt8)(INST_top.INST_m_wr_addrOut_rv.METH_port0__read() >> 35u)) && !INST_top.DEF_m_wr_dataOut_rv_port0__read____d26.get_bits_in_word8(2u,
																																	   8u,
																																	   1u));
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_splitAddrData = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_splitAddrData;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_splitAddrData)
	   INST_top.RL_m_wr_splitAddrData();
	 INST_top.DEF_m_wr_addrOut_rv_port1__read____d37 = INST_top.INST_m_wr_addrOut_rv.METH_port1__read();
	 INST_top.DEF_m_wr_addrOut_rv_port1__read__7_BIT_35___d38 = (tUInt8)((INST_top.DEF_m_wr_addrOut_rv_port1__read____d37) >> 35u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqAddr = INST_top.DEF_m_wr_addrOut_rv_port1__read__7_BIT_35___d38 && (INST_top.DEF_NOT_m_wr_isRst_isInReset_0___d39 && INST_top.INST_m_wr_awreadyIn.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqAddr = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqAddr;
	 INST_top.DEF_m_wr_dataOut_rv_port1__read____d45 = INST_top.INST_m_wr_dataOut_rv.METH_port1__read();
	 INST_top.DEF_m_wr_dataOut_rv_port1__read__5_BIT_72___d46 = INST_top.DEF_m_wr_dataOut_rv_port1__read____d45.get_bits_in_word8(2u,
																      8u,
																      1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqData = INST_top.DEF_m_wr_dataOut_rv_port1__read__5_BIT_72___d46 && (INST_top.DEF_NOT_m_wr_isRst_isInReset_0___d39 && INST_top.INST_m_wr_wreadyIn.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqData = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_deqData;
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardAddr = INST_top.DEF_m_wr_addrOut_rv_port1__read__7_BIT_35___d38;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardAddr = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardAddr;
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardData = INST_top.DEF_m_wr_dataOut_rv_port1__read__5_BIT_72___d46;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardData = DEF_INST_top_DEF_CAN_FIRE_RL_m_wr_forwardData;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward2_1)
	   INST_top.RL_forward2_1();
	 INST_top.INST_s_mul.DEF_NOT_slave_write_addrIn_rv_port0__read__5_BIT_35_6___d37 = !((tUInt8)(INST_top.INST_s_mul.INST_slave_write_addrIn_rv.METH_port0__read() >> 35u));
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_addrInWrite = (INST_top.INST_s_mul.DEF_NOT_slave_write_addrIn_rv_port0__read__5_BIT_35_6___d37 && (INST_top.INST_s_mul.DEF_NOT_slave_write_isRst_isInReset_1___d38 && INST_top.INST_s_mul.INST_slave_write_awvalidIn.METH_wget())) && !DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_addrInWrite = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_addrInWrite;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward6_1)
	   INST_top.RL_forward6_1();
	 INST_top.INST_s_mul.DEF_slave_write_dataIn_rv_port0__read____d45 = INST_top.INST_s_mul.INST_slave_write_dataIn_rv.METH_port0__read();
	 INST_top.INST_s_mul.DEF_NOT_slave_write_dataIn_rv_port0__read__5_BIT_72_6___d47 = !INST_top.INST_s_mul.DEF_slave_write_dataIn_rv_port0__read____d45.get_bits_in_word8(2u,
																					       8u,
																					       1u);
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_dataInWrite = (INST_top.INST_s_mul.DEF_NOT_slave_write_dataIn_rv_port0__read__5_BIT_72_6___d47 && (INST_top.INST_s_mul.DEF_NOT_slave_write_isRst_isInReset_1___d38 && INST_top.INST_s_mul.INST_slave_write_wvalidIn.METH_wget())) && !DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_isRst_isResetAssertedUpdate;
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_dataInWrite = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_dataInWrite;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardAddr)
	   INST_top.RL_m_wr_forwardAddr();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward3_1)
	   INST_top.RL_forward3_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward4_1)
	   INST_top.RL_forward4_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqAddr)
	   INST_top.RL_m_wr_deqAddr();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_forwardData)
	   INST_top.RL_m_wr_forwardData();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward7_1)
	   INST_top.RL_forward7_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_forward8_1)
	   INST_top.RL_forward8_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_deqData)
	   INST_top.RL_m_wr_deqData();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_wr_isRst_isResetAssertedUpdate)
	   INST_top.RL_m_wr_isRst_isResetAssertedUpdate();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_read_addrInWrite)
	   INST_top.INST_s_mul.RL_slave_read_addrInWrite();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleReadRequest)
	   INST_top.INST_s_mul.RL_handleReadRequest();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_product_operation)
	   INST_top.INST_s_mul.RL_product_operation();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_addrInWrite)
	   INST_top.INST_s_mul.RL_slave_write_addrInWrite();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_dataInWrite)
	   INST_top.INST_s_mul.RL_slave_write_dataInWrite();
	 INST_top.INST_s_mul.DEF_slave_write_dataIn_rv_port1__read____d24 = INST_top.INST_s_mul.INST_slave_write_dataIn_rv.METH_port1__read();
	 INST_top.INST_s_mul.DEF_slave_write_addrIn_rv_port1__read____d22 = INST_top.INST_s_mul.INST_slave_write_addrIn_rv.METH_port1__read();
	 DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_mergeAddrData = (tUInt8)((INST_top.INST_s_mul.DEF_slave_write_addrIn_rv_port1__read____d22) >> 35u) && (INST_top.INST_s_mul.DEF_slave_write_dataIn_rv_port1__read____d24.get_bits_in_word8(2u,
																															8u,
																															1u) && INST_top.INST_s_mul.INST_slave_write_in.METH_i_notFull());
	 DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_mergeAddrData = DEF_INST_top_INST_s_mul_DEF_CAN_FIRE_RL_slave_write_mergeAddrData;
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_mergeAddrData)
	   INST_top.INST_s_mul.RL_slave_write_mergeAddrData();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_slave_write_outWrite)
	   INST_top.INST_s_mul.RL_slave_write_outWrite();
	 if (DEF_INST_top_INST_s_mul_DEF_WILL_FIRE_RL_handleWriteRequest)
	   INST_top.INST_s_mul.RL_handleWriteRequest();
	 INST_top.INST_m_wr_brespIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_bvalidIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_wstrbOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_wdataOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_wreadyIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_awprotOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_awaddrOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_awreadyIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_dataOut_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_addrOut_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_out_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_wr_in_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_rrespIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_rdataIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_rvalidIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_arprotOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_araddrOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_arreadyIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_out_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_rd_in_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_brespOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_breadyIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_wstrbIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_wdataIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_wvalidIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_awprotIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_awaddrIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_awvalidIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_dataIn_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_write_addrIn_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_rrespOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_rdataOut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_rreadyIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_arprotIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_araddrIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_mul.INST_slave_read_arvalidIn.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_s_mul.INST_slave_read_isRst_isInReset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_read_in.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_read_out.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_write_isRst_isInReset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_write_in.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_write_out.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_write_addrIn_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_slave_write_dataIn_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_mul.INST_operand_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s_mul.INST_operand_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s_mul.INST_product.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_testState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_rd_isRst_isInReset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_rd_in_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_rd_out_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_wr_isRst_isInReset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_wr_in_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_wr_out_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_wr_addrOut_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_wr_dataOut_rv.rst_tick_clk((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkAXIMultiplier_tb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkAXIMultiplier_tb_instance = new MOD_mkAXIMultiplier_tb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkAXIMultiplier_tb_instance->INST_m_rd_in_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_out_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_arreadyIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_araddrOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_arprotOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_rvalidIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_rdataIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_rd_rrespIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_in_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_out_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_addrOut_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_dataOut_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_awreadyIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_awaddrOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_awprotOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_wreadyIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_wdataOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_wstrbOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_bvalidIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_m_wr_brespIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_in.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_out.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_arvalidIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_araddrIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_arprotIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_rreadyIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_rdataOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_read_rrespOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_in.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_out.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_addrIn_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_dataIn_rv.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_awvalidIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_awaddrIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_awprotIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_wvalidIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_wdataIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_wstrbIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_breadyIn.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.INST_slave_write_brespOut.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->INST_s_mul.set_clk_0)("CLK");
  (mkAXIMultiplier_tb_instance->set_clk_0)("CLK");
}
void MODEL_mkAXIMultiplier_tb::destroy_model()
{
  delete mkAXIMultiplier_tb_instance;
  mkAXIMultiplier_tb_instance = NULL;
}
void MODEL_mkAXIMultiplier_tb::reset_model(bool asserted)
{
  (mkAXIMultiplier_tb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkAXIMultiplier_tb::get_instance()
{
  return mkAXIMultiplier_tb_instance;
}

/* Fill in version numbers */
void MODEL_mkAXIMultiplier_tb::get_version(unsigned int *year,
					   unsigned int *month,
					   char const **annotation,
					   char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "e76ca21";
}

/* Get the model creation time */
time_t MODEL_mkAXIMultiplier_tb::get_creation_time()
{
  
  /* Mon Dec 28 12:16:08 UTC 2020 */
  return 1609157768llu;
}

/* State dumping function */
void MODEL_mkAXIMultiplier_tb::dump_state()
{
  (mkAXIMultiplier_tb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkAXIMultiplier_tb & mkAXIMultiplier_tb_backing(tSimStateHdl simHdl)
{
  static MOD_mkAXIMultiplier_tb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkAXIMultiplier_tb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkAXIMultiplier_tb::dump_VCD_defs()
{
  (mkAXIMultiplier_tb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkAXIMultiplier_tb::dump_VCD(tVCDDumpType dt)
{
  (mkAXIMultiplier_tb_instance->dump_VCD)(dt,
					  vcd_depth(sim_hdl),
					  mkAXIMultiplier_tb_backing(sim_hdl));
}
